volumes:
  springSecDb:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: springSecDb

    ports:
      - "5432:5432"

    volumes:
      - springSecDb:/var/lib/postgresql/data